# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  magicvillavillaapi:
    image: magicvillavillaapi
    build:
      context: .
      dockerfile: MagicVilla_VillaAPI/Dockerfile
    ports:
      - 5145:5145
